
/*const REWARD_TRICK_CLUBS: i64 = 20;
const REWARD_TRICK_DIAMONDS: i64 = 20;
const REWARD_TRICK_HEARTS: i64 = 30;
const REWARD_TRICK_SPADES: i64 = 30;

const REWARD_TRICK_FIRST_NO_TRUMP: i64 = 40;
const REWARD_TRICK_SUBSEQUENT_NO_TRUMP: i64 = 30;

// # Overtricks:
const REWARD_OVERTRICK_CLUBS_UNDOUBLED: i64 = 20;
const REWARD_OVERTRICK_DIAMONDS_UNDOUBLED: i64 = 20;
const REWARD_OVERTRICK_HEARTS_UNDOUBLED: i64 = 30;
const REWARD_OVERTRICK_SPADES_UNDOUBLED: i64 = 30;

const REWARD_OVERTRICK_CLUBS_UNDOUBLED_VULNERABLE: i64 = 20;
const REWARD_OVERTRICK_DIAMONDS_UNDOUBLED_VULNERABLE: i64 = 20;
const REWARD_OVERTRICK_HEARTS_UNDOUBLED_VULNERABLE: i64 = 20;
const REWARD_OVERTRICK_SPADES_UNDOUBLED_VULNERABLE: i64 = 20;

const REWARD_OVERTRICK_CLUBS_DOUBLED: i64 = 100;
const REWARD_OVERTRICK_DIAMONDS_DOUBLED: i64 = 100;
const REWARD_OVERTRICK_HEARTS_DOUBLED: i64 = 100;
const REWARD_OVERTRICK_SPADES_DOUBLED: i64 = 100;

const REWARD_OVERTRICK_CLUBS_DOUBLED_VULNERABLE: i64 = 200;
const REWARD_OVERTRICK_DIAMONDS_DOUBLED_VULNERABLE: i64 = 200;
const REWARD_OVERTRICK_HEARTS_DOUBLED_VULNERABLE: i64 = 200;
const REWARD_OVERTRICK_SPADES_DOUBLED_VULNERABLE: i64 = 200;

const REWARD_OVERTRICK_CLUBS_REDOUBLED: i64 = 200;
const REWARD_OVERTRICK_DIAMONDS_REDOUBLED: i64 = 200;
const REWARD_OVERTRICK_HEARTS_REDOUBLED: i64 = 200;
const REWARD_OVERTRICK_SPADES_REDOUBLED: i64 = 200;

const REWARD_OVERTRICK_CLUBS_REDOUBLED_VULNERABLE: i64 = 400;
const REWARD_OVERTRICK_DIAMONDS_REDOUBLED_VULNERABLE: i64 = 400;
const REWARD_OVERTRICK_HEARTS_REDOUBLED_VULNERABLE: i64 = 400;
const REWARD_OVERTRICK_SPADES_REDOUBLED_VULNERABLE: i64 = 400;

*/